module.exports = {
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true,
    "jquery":true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "indent": ["warn", 2],
    "linebreak-style": ["error", "unix"],
    "quotes": ["warn", "single"],
    "semi": ["error", "always"],
    "no-console" : ["off"],
    "camelcase" : ["off"],

    // Possible Errors

    // no-constant-condition: ["error", { "checkLoops": false }],

    // Rule Best Practices
    "accessor-pairs": ["error"],
    "array-callback-return": ["error"],
    "block-scoped-var": ["error"],
    "complexity": ["warn", 6],
    "consistent-return": ["error"],
    "curly": ["error"],
    "default-case": ["warn"],
    "dot-location": ["off"],
    "dot-notation": ["warn"],
    "eqeqeq": ["error"],
    "guard-for-in": ["off"],
    "no-alert": ["off"],
    "no-caller": ["error"],
    //    "no-case-declarations": ["error"],
    "no-div-regex": ["error"],
    "no-else-return": ["warn"],
    "no-empty-function": ["error"],
    //    "no-empty-pattern": ["error"],
    "no-eq-null": ["error"],
    "no-eval": ["error"],
    "no-extend-native": ["warn"],
    "no-extra-bind": ["error"],
    "no-extra-label": ["error"],
    //    "no-fallthrough": ["error"],
    "no-floating-decimal": ["error"],
    "no-implicit-coercion": ["warn"],
    "no-implicit-globals": ["error"],
    "no-implied-eval": ["warn"],
    "no-invalid-this": ["error"],
    "no-iterator": ["error"],
    "no-labels": ["error"],
    "no-lone-blocks": ["error"],
    "no-loop-func": ["error"],
    "no-magic-numbers": ["off"],
    "no-multi-spaces": ["off"],
    "no-multi-str": ["error"],
    //    "no-native-reassign": ["error"],
    "no-new-func": ["error"],
    "no-new-wrappers": ["error"],
    "no-new": ["error"],
    "no-octal-escape": ["error"],
    //    "no-octal": ["error"],
    "no-param-reassign": ["warn"],
    "no-proto": ["error"],
    //    "no-redeclare": ["error"],
    "no-return-assign": ["error"],
    "no-script-url": ["error"],
    //    "no-self-assign": ["error"],
    "no-self-compare": ["error"],
    "no-sequences": ["error"],
    "no-throw-literal": ["error"],
    "no-unmodified-loop-condition": ["error"],
    "no-unused-expressions": ["error"],
    //    "no-unused-labels": ["error"],
    "no-useless-call": ["error"],
    "no-useless-concat": ["error"],
    "no-useless-escape": ["error"],
    "no-void": ["error"],
    "no-warning-comments": ["warn"],
    "no-with": ["error"],
    "radix": ["error"],
    "vars-on-top": ["off"],
    "wrap-iife": ["error"],
    "yoda": ["error"],

    // Rule Variables
    "init-declarations": ["off"],
    "no-catch-shadow": ["error"],
    //    "no-delete-var" : ["error"],
    "no-label-var": ["error"],
    "no-restricted-globals": ["error"],
    "no-shadow-restricted-names": ["error"],
    "no-shadow": ["warn"],
    "no-undef-init": ["warn"],
    //    "no-undef" : ["error"],
    "no-undefined": ["error"],
    "no-unused-vars" : ["warn"],
    "no-use-before-define": ["off"],

    // Rule Node.js and CommonJS
    "callback-return": ["error"],
    "global-require": ["error"],
    "handle-callback-err": ["error"],
    "no-mixed-requires": ["error"],
    "no-new-require": ["error"],
    "no-path-concat": ["error"],
    "no-process-env": ["off"],
    "no-process-exit": ["warn"],
    "no-restricted-modules": ["error"],
    "no-sync": ["off"],

    // Rule Stylistic Issues
    "array-bracket-spacing": ["warn"],
    "block-spacing": ["warn"],
    "brace-style": ["off"],
    "camelcase": ["warn", { "properties": "always" }],
    "comma-dangle": ["error"],
    "comma-spacing": ["warn"],
    "comma-style": ["off"],
    "computed-property-spacing": ["off"],
    "consistent-this": ["warn", "self"],
    "eol-last": ["off"],
    "func-names": ["off"],
    "func-style": ["off"],
    "id-blacklist": ["error"],
    "id-length": ["warn", { "min": 1, "max": 18, "properties": "never", "exceptions": ["x"] }],
    "id-match": ["off"],
    "indent": ["warn", 2],
    "jsx-quotes": ["off"],
    "key-spacing": ["off"],
    "keyword-spacing": ["warn"],
    "linebreak-style": ["error", "unix"],
    "lines-around-comment": ["warn"],

    "no-array-constructor": ["warn"],
    "no-bitwise": ["warn"],
    "no-continue": ["warn"],
    "no-inline-comments": ["off"],
    "no-lonely-if": ["warn"],
    "no-mixed-operators": ["warn"],
    "no-mixed-spaces-and-tabs": ["warn"],
    "no-multiple-empty-lines": ["warn", { max: 4 }],
    "no-negated-condition": ["warn"],
    "no-nested-ternary": ["error"],
    "no-new-object": ["error"],
    "no-plusplus": ["off"],
    "no-restricted-syntax": ["off"],
    "no-spaced-func": ["warn"],
    "no-ternary": ["off"],
    "no-trailing-spaces": ["warn"],
    "no-underscore-dangle": ["off"],

    "no-unneeded-ternary": ["error"],
    "no-whitespace-before-property": ["error"],
    "object-curly-newline": ["off"],
    "object-curly-spacing": ["error", "never"],
    "object-property-newline": ["off"],
    "one-var-declaration-per-line": ["off"],
    "one-var": ["off"],
    "operator-assignment": ["off"],
    "operator-linebreak": ["warn", "before"],
    "padded-blocks": ["off"],
    "quote-props": ["warn", "as-needed"],
    "quotes": ["warn", "single"],
    "require-jsdoc": ["off"],
    "semi-spacing": ["warn"],
    "semi": ["error", "always"],
    "sort-vars": ["off"],
    "space-before-blocks": ["warn"],
    "space-before-function-paren": ["warn", "never"],
    "space-in-parens": ["warn", "never"],
    "space-infix-ops": ["warn"],
    "space-unary-ops": ["warn"],
    "spaced-comment": ["off"],
    "unicode-bom": ["warn"],
    "wrap-regex": ["error"]
  }
};